name: Build site and publish
on: push
jobs:
  jekyll:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Standard usage
      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
        with:
          jekyll_src: "./"
          target_branch: "build"
        id: 'build'
      
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      
      # - name: Call Hook PROD success
      #   uses: distributhor/workflow-webhook@v1
      #   if: steps.build.outputs.status == 'failure' || steps.world.outputs.status == 'failure'
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL_PROD }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     data: '{ "status": "hammer", "drink" : "beer" }'
      # - name: Call Hook
      #   uses: distributhor/workflow-webhook@v1
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL_STAGING }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     data: '${{ steps.build.outputs }}'
      # - name: Call Hook
      #   uses: distributhor/workflow-webhook@v1
      #   env:
      #     webhook_url: ${{ secrets.WEBHOOK_URL_LOCAL }}
      #     webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      #     data: '${{ steps.build.outputs }}'
